---
driver_plugin: docker
driver_config:
  require_chef_omnibus: true

platforms:
- name: debian-6
  driver_config:
    image: inokappa/wheezy-7.2-basic
    socket: tcp://127.0.0.1:4243
suites:
- name: default
  run_list: [
    "recipe[elasticsearch_cookbook::apt_update]",
    "recipe[elasticsearch_cookbook::app_install]",
]
  attributes: {}
